--return {
--  "nvim-tree/nvim-tree.lua", thisi
--  version = "*",
--  lazy = false,
--  dependencies = {
--    "nvim-tree/nvim-web-devicons",
--  },
--  config = function()
--    require("nvim-tree").setup {}
--  end,
--}
--
